### ISSUE TITLE
Final newline?

### ISSUE THREAD

**Issue by telemachus** [jeffzi/llscheck#3]
This is a minor thing, but the output does not seem to include a final newline. Is that intentional?

**Comment by jeffzi** [comment]
It wasn't intentional, my setup did not make the missing newline obvious 😓 

<img width="540" alt="image" src="https://github.com/user-attachments/assets/e05b4dfa-7151-4d46-ba27-430ee5e26bad">

You can try the fix with `luarocks install https://raw.githubusercontent.com/jeffzi/llscheck/main/llscheck-dev-1.rockspec` until a new release comes out.

**Comment by telemachus** [comment]
Terrific. Thanks.
